### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by GazTheGeek** [sebirdman/hass_traeger#71]
## Version of the custom_component
v0.0.8

## Configuration
I installed as per the instructions. Added files to a new 'traeger' folder in custom_components folder.
```yaml

Add your logs here.
No logs - I don't think we got that far

```

## Describe the bug

After copying the files in the traeger folder of this repository into a new folder called traeger in my custom_components folder I tried to install the integration via the ui in my home assistant instance. It found the integration fine but imediately threw an error Config flow could not be loaded: {"message":"Invalid handler specified"}

## Debug log

```text

Add your logs here.

```

**Comment by draigo-lives** [comment]
Logs should have shown an error about TEMP_CELSIUS being depreciated. I fixed the errors on my local machine and got it to work just fine. I've enclosed a zip file with the fixes. I don't have the drive to put in a pull request/etc to push the files to the repo right now as I have a brisket on the smoker, but the files should work.

[custom_components.zip](https://github.com/user-attachments/files/20447752/custom_components.zip)

**Comment by draigo-lives** [comment]
Quick update - decided to fork the repo and propose the changes because it was going to bother me if I didn't now. Anyway, the issue should be fixed.

**Comment by GazTheGeek** [comment]
Thanks draigo. Its so great that someone I don't know would go to the trouble to help. Un fortunately I tried with he new code. I downloaded the zip you included above and restarted HA. But I'm still getting the same error when I try to add the integration.

Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by draigo-lives** [comment]
Ah shoot - could you verify there are no logs that identify any specific errors? I know there are some errors being thrown in the .zip files I provided that limit some of the integration's functionality (looking to fix that as well) but I'm hoping those errors aren't causing this specific issue.

**Comment by GazTheGeek** [comment]
I rechecked the logs. The core log had this error.

`Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: May 27, 2025 at 2:22:35 PM (2 occurrences)
Last logged: May 27, 2025 at 2:22:35 PM

Config was used from traeger, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'traeger' custom integration
Config was used from traeger, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please create a bug report at https://github.com/sebirdman/hass_traeger/issues`

I tried reloading the integration and now I also get this error:

`Logger: homeassistant.config_entries
Source: config_entries.py:3761
First occurred: May 27, 2025 at 2:22:35 PM (2 occurrences)
Last logged: 10:04:22 AM

Error occurred loading flow for integration traeger: cannot import name 'CELSIUS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
`

I cannot see any other errors. Is there somewhere specific you would expect to see a log entry?

**Comment by draigo-lives** [comment]
Gotcha - I'm working on addressing this. I'm testing some stuff on my local HA machine/Traeger and as soon as I find a solution I'll post the .zip file and push an update for the code owner to review.

**Comment by GazTheGeek** [comment]
Thanks so much.

**Comment by draigo-lives** [comment]
Ok I think I have it working full again, at least on my setup. Please test and let me know!! I've put a few updates in my Fork as well, hoping the original owner will approve and merge the requests for users who still want to use it.

Here's the file: Let me know what you think!

[traeger.zip](https://github.com/user-attachments/files/20473657/traeger.zip)

**Comment by GazTheGeek** [comment]
Thanks @draigo-lives. I copied the files in the zip above.

I noted a file called 'sensor (1).py' so I renamed it 'sensor.py'. I restarted my HA Instance.

Looks good so far. No error and I was able to add my credendials and the device appeared.

I haven't fired it up yet but certainly made it a lot further than before.

Thanks heaps.

G

**Comment by nelway42** [comment]
Thank you @draigo-lives !  I copied your modifications and my grill is now showing up.  Like @GazTheGeek I haven't fired it up yet but this is huge progress.

For anyone else who doesn't like installing code from random zip files, I did a line-by-line review of the changes before I installed it, and didn't have any concerns, it's good work.

**Comment by draigo-lives** [comment]
Thank you @nelway42! If you guys are looking for the probe to be connected as well, I'd recommend this fork of the repo: https://github.com/njobrien1006/hass_traeger. They did an excellent job and I ended up folding a lot of their code into the files I updated for my HA instance. I highly recommend their fork - wish I found it sooner haha.
cc: @GazTheGeek

**Comment by nelway42** [comment]
Thanks for the recommendation!

**Comment by johnvoipguy** [comment]
There is a re-write to this available [HERE](https://github.com/johnvoipguy/Traeger-WiFire)
